---
#
# Master Install
#
# Installs _the_ world
#

- hosts: all
  sudo: True
  roles:
    - { role: ansible-docker, tags:['os-tools'] }
    - { role: ansible-nodejs, node_version: "0.10.24", tags:['runtimes']}
    - { role: ansible-java, java_version: "7", tags:['runtimes']}
    - { role: ansible-scala, scala_version: "2.10.3", tags:['runtimes'] }
    - { role: ansible-sbt, sbt_version: "0.13.1", tags:['scala-tools'] }
    - { role: ansible-mesos, mesos_version: "0.15.0", tags:['mesos', 'platforms'] }
    - { role: ansible-marathon, marathon_version: "marathon-0.3.0", tags:['mesos-tools'] }
    - { role: ansible-chronos, chronos_version: "2.1.0", tags:['mesos-tools'] }
    - { role: ansible-mesos-docker, mesos_docker_branch: "master", tags:['mesos-tools'] }

- include: integration-tests.yml
