---

# Master Install
#
# Installs _the_ world
#

- hosts: all
  sudo: True
  roles:  
    - { role: ansible-docker }
    - { role: ansible-nodejs, node_version: "0.10.24" }
    - { role: ansible-java, java_version: "7" }
    - { role: ansible-scala, scala_version: "2.10.3" }
    - { role: ansible-sbt, sbt_version: "0.13.1" }
    - { role: ansible-mesos, mesos_version: "0.15.0" }
    - { role: ansible-marathon, marathon_version: "marathon-0.3.0" }
    - { role: ansible-chronos, chronos_version: "2.1.0" }
    - { role: ansible-mesos-docker, mesos_docker_branch: "master" }
